# Generated by Django 3.2.5 on 2021-07-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_board',
            fields=[
                ('brd_uid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('cntnt', models.CharField(max_length=1000)),
                ('rgst_dttm', models.DateTimeField(blank=True, null=True)),
                ('updt_dttm', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_board',
            },
        ),
    ]
