# Generated by Django 3.2.5 on 2021-07-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapiapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='t_board',
        ),
    ]
